### ISSUE TITLE
unexpected behavior Animation.js

### ISSUE THREAD

**Issue by acosinwork** [amperka/espruino-modcat#22]
@nailxx 
@niggor 

https://github.com/amperka/espruino-modcat/blob/master/modules/%40amperka/animation.js#L64-L73

https://github.com/amperka/espruino-modcat/blob/master/modules/%40amperka/animation.js#L68
Когда я говорю анимации stop(),  я совсем не ожидаю, что она вызовет update распоследний раз со значениями таргета. Я жду, что горшочек перестанет варить. Ну и это поведение не описано в http://wiki.amperka.ru/js:animation

Давайте это уберём?
Так как похоже, что это "уберём" поломает эксперимент 23 в Йоде, то предлагаю добавить опцию
`this._updateOnStopWithTarget  = opts.updateOnStopWithTarget || true;`
Чего докопался?
Представим, что у нас пыточный станок, повышающий напряжение на голове испытуемого от 0 до 1000 В до тех пор, пока он не расскажет, где печеньки.
На 100 В он признался, что в тумбочке. Палач говорит ок, stop()... и тут ФИГАК - котлета!
Палач будет озадачен

**Comment by nailxx** [comment]
Текущее поведение повторяет то, как это происходит в jQuery. Предлагаю не мудрить, а добавить в `stop` параметр вроде `skip`, который по умолчанию был бы `true` (текущее поведение), а `false` приводил бы к тому поведению, которое ты описываешь.
