### ISSUE TITLE
gas-sensor

### ISSUE THREAD

**Issue by altishchenko** [amperka/espruino-modcat#29]
Please, add the @amperka/gas-sensor ! (And it is not visible from the Espruino Web IDE either...)

**Comment by nailxx** [comment]
@r1000ru, please, note this.

**Comment by r1000ru** [comment]
The module works, but returns results not attainable in the conditions of the Earth. Keep experimenting with coeficients.

**Comment by altishchenko** [comment]
How about "Module not found" error message?
Модуль не найден. Его нет.

**Comment by altishchenko** [comment]
@r1000ru а в TroykaMQ значения разумные?

**Comment by r1000ru** [comment]
Данная библиотека будет выложена в общей доступ в течении недели. На данный момент показания сенсоров газа не коррелируют параметрами из документации.

**Comment by altishchenko** [comment]
@r1000ru Понятно, а про TroykaMQ для Arduino? Там значения разумные или тоже не особо?

**Comment by altishchenko** [comment]
@r1000ru Большое спасибо!
