### ISSUE TITLE
Библиотека @amperka/ir-receiver. Ошибка

### ISSUE THREAD

**Issue by LDWork** [amperka/espruino-modcat#93]
В этой строке прописан путь к  ir-remote-controller.js

https://github.com/amperka/espruino-modcat/blob/5e38b25c38178c1931bf65c394e088a7c0e133dc/modules/%40amperka/ir-receiver.js#L15

Если локально стоят библиотеки, то не работает

**Comment by igor605ds** [comment]
@kekcheburec проверишь?

**Comment by kekcheburec** [comment]
@igor605ds проверил, так и есть. Фикс довольно простой, просто перенести KEY_CODES в файл ir-receiver.js вместо импорта.

**Comment by kekcheburec** [comment]
#94
